# Generated by Django 3.2.3 on 2021-10-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211027_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='apple',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='header',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='header',
            name='navlogo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
