# Generated by Django 3.2.3 on 2021-10-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211027_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='mision_vision',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mision_vision',
            name='img',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='Home/'),
        ),
    ]
