# Generated by Django 3.2.3 on 2021-10-27 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_mision_vision_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='title_ar',
        ),
    ]
